name: Diag • Telegram ping

on:
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send message via Telegram Bot API
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          set -euo pipefail
          if [ -z "${TG_TOKEN}" ]; then echo "❌ Missing TG_TOKEN"; exit 1; fi
          if [ -z "${TG_CHAT_ID}" ]; then echo "❌ Missing TG_CHAT_ID"; exit 1; fi
          RESP=$(curl -sS -X POST "https://api.telegram.org/bot${TG_TOKEN}/sendMessage" \
            -d chat_id="${TG_CHAT_ID}" \
            --data-urlencode text="Ping ✅ from GitHub Actions")
          echo "Telegram response:"
          echo "${RESP}"
          echo "${RESP}" | grep -q '"ok":true' || { echo "❌ Telegram returned error"; exit 1; }
