name: NBA standings to Telegram

on:
  workflow_dispatch:
  schedule:
    - cron: "5 5 * * *"  # каждый день ~08:05 по Европе/Хельсинки (cron в UTC)

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Syntax check
        run: python -m py_compile nba_standings_bot.py

      - name: Run bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python nba_standings_bot.py
